<?php

namespace App\Console\Commands;

use App\Jobs\SendEmail;
use App\Models\Customer;
use App\Models\Invoice;
use App\Models\Order;
use App\Models\Ticket;
use App\Models\User;
use Illuminate\Console\Command;

/**
 * Send a periodic business-summary report to admin/staff.
 *
 * Fills the plan's `reports:send-scheduled` gap (2 of the original 6 scheduled
 * commands). Aggregates headline metrics over the trailing period and emails
 * them to staff users via the SendEmail queue job. Run manually with
 * `--to=you@example.com` to override the recipient list.
 */
class ScheduledReportsCommand extends Command
{
    protected $signature = 'reports:send-scheduled {--days=7 : Reporting window} {--to=* : Override recipient emails}';

    protected $description = 'Email a business summary report to admin/staff';

    public function handle(): int
    {
        $days = (int) $this->option('days');
        $since = now()->subDays($days)->startOfDay();

        $newCustomers = Customer::where('created_at', '>=', $since)->count();
        $newOrders = Order::where('created_at', '>=', $since)->count();
        $revenue = (float) Invoice::where('status', 'paid')
            ->where('paid_at', '>=', $since)
            ->sum('total');
        $openTickets = Ticket::whereIn('status', ['open', 'pending'])->count();
        $paidInvoices = Invoice::where('status', 'paid')
            ->where('paid_at', '>=', $since)
            ->count();

        $subject = "Business Summary — last {$days} days";
        $body = implode("\n", [
            "Period: {$since->toDateString()} → ".now()->toDateString(),
            '',
            str_repeat('-', 32),
            "New customers: {$newCustomers}",
            "New orders:    {$newOrders}",
            "Paid invoices: {$paidInvoices}",
            'Revenue (paid): '.'₹'.number_format($revenue, 2),
            'Open tickets:  '.$openTickets,
            str_repeat('-', 32),
            'Generated by '.now()->format('Y-m-d H:i'),
        ]);

        // Prefer explicit --to overrides; otherwise notify staff+admin roles.
        $recipients = collect($this->option('to'))
            ->flatten()
            ->filter()
            ->whenEmpty(function () {
                return User::whereIn('role', ['admin', 'staff', 'support'])
                    ->where('status', 'active')
                    ->pluck('email');
            });

        $dispatched = 0;
        foreach ($recipients->unique() as $email) {
            if (filter_var($email, FILTER_VALIDATE_EMAIL)) {
                SendEmail::dispatch($email, $subject, $body);
                $dispatched++;
            }
        }

        $this->info('Scheduled report dispatched to '.$dispatched.' recipient(s).');
        $this->line('  New customers: '.$newCustomers.' | Orders: '.$newOrders.' | Revenue: ₹'.number_format($revenue, 2).' | Open tickets: '.$openTickets);

        return self::SUCCESS;
    }
}
